# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0003_auto_20160617_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='idx',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ware',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
