# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0004_auto_20160617_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='idx',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ware',
            name='provider_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ware',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
