# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0005_auto_20160617_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
