# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0006_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storehouse.Provider'),
            preserve_default=False,
        ),
    ]
