# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0007_ware_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=50)),
                ('productparts', models.ManyToManyField(related_name='_product_productparts_+', to='storehouse.Product')),
                ('wareparts', models.ManyToManyField(to='storehouse.Ware')),
            ],
        ),
    ]
