# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_open',
            field=models.BooleanField(default=True),
        ),
    ]
