# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0014_auto_20160622_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
